### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by loeiten** [boutproject/boututils#19]
I suggest to add some linting through pre-commit in order to automatically ensure that the code is readable. The timing of this introduction can be good now as there are not any PR which will get strange merge conflicts due to this.

Specifically I'm suggesting to use `black`, `isort` and `flake8` as the bare minimum, and maybe `pylint` and `mypy` at a later stage

Something like the following should work:

`.pre-commit-config.yaml`

```yaml
# NOTE: The versions can be updated by calling
#        pre-commit autoupdate
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/prettier/pre-commit
    rev: 413fd9da8e03249b74acf8543567e5debbad8bfa
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]

  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
```

`setup.cfg`

```cfg
[isort]
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
ensure_newline_before_comments = True
line_length = 88

[flake8]
max-line-length = 88
extend-ignore = E203, W503
docstring-convention = numpy
```

`.github/workflows/lint.yml`

```yaml
name: Lint

on:
  # Run each time we push and pull requests
  push:
  pull_request:
  # Cron job
  # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
  schedule:
    # https://crontab.guru/#0_0_1_*_*
    - cron: "0 0 1 * *"

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      # Use the v2 tag of: https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Python ${{ matrix.python-version }}
        # Use the v2 tag of: https://github.com/actions/setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # https://github.com/PyCQA/pylint/issues/352
        # pylint need the requirements to do the checks as the pre-commit repo is local
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
          pip install .

      - name: Lint
        run: pre-commit run --all-files
```
